### ISSUE TITLE
toDos (in progress) 

### ISSUE THREAD

**Issue by juliuspfadt** [jasp-stats/jaspBfpack#1]
### Issues with JASP: 
-

### Issues with BFpack: 
- why do you not allow a hypothesis such as "contNormal_with_contGamma !=0"

**Comment by juliuspfadt** [comment]
So the thing with the different results for equivalent standard and manual hypotheses is due to the BF.type argument that is `BF.type=1` by default in JASP, meaning the fractional BF is the default. This actually leads to the differences. The default in BFpack however is `BF.type = 2`, meaning the adjusted fractional BF. so now I changed the default in JASP as well, et voila it works as expected.

**Comment by jomulder** [comment]
> So the thing with the different results for equivalent standard and manual hypotheses is due to the BF.type argument that is `BF.type=1` by default in JASP, meaning the fractional BF is the default. This actually leads to the differences. The default in BFpack however is `BF.type = 2`, meaning the adjusted fractional BF. so now I changed the default in JASP as well, et voila it works as expected.

Ah that's lame. Sorry about that!

**Comment by jomulder** [comment]
- [ ] * the number of iterations in the correlation test does not seem to work (always the default iter=5e3 in the cor_test() function seems to be used).
- [ ] * cor_test() also has an argument 'nugget.scale'. I think it would be good to add it to the module as well (maybe set the default to .999 or something). In case of very small samples and extreme observations, e.g., when the cor estimate is very close to 1, the MCMC sometimes gets stuck close to 1, and this nugget.scale would fix that by setting it to a slightly smaller value if needed. I can add info in the help file on this of course.
- [ ] * in case of a grouping variance in the correlation test, only the posteriors and traceplots of the first group seem to be shown.
- [ ] * For the independent samples t-test, include an option var.equal=TRUE/FALSE (default TRUE). In case var.equal=FALSE, the iter argument (default 1e6) is used, and thus, would be needed as an additional option in that case.
- [ ] * In the independent samples t-test, I see infinity in the second last 'BF' column in the specification table. I do not see this in the 'BFtable_confirmatory' element of the BF object in R. Do you compute it manually in the module? Maybe better to extract it from the 'BFtable_confirmatory' element of the BF object?
- [ ] * The BFs for the standard test are tested against the unconstrained hypothesis rather than the 'complement'. But I think you already fixed this....
- [ ] * For the linear regression model and (M)AN(C)OVA, it would be nice to include a checkbox of whether the scale variables need to be standardized. In bain, this is more complex because standardization can be done in different ways in a SEM (I think). But here it is just very straightforward by standardizing the dependent/predictor variables with scale measurement level. The reason that this is particularly useful is because when testing coefficients in a regression model, say, beta1>beta2, this only makes sense if the scale of the predictors is the same.
- [ ] * For the logistic regression model, it would be nice if it can handle a nominal DV having two levels (via a glm() base analysis), as well as an ordinal DV (via a MASS::polr() analysis). I think you already implemented though...
- [ ] * Multivariate t test. JASP does not do anything when only one variable is included. Maybe we want to keep it this way but in R, a simple t test would be executed then (without needing to change the syntax for the multivariate t test using the mvt_test() function).
- [ ] * Multivariate t test. Test values cannot be aligned? Sorry for this question if you already told me...

**Comment by juliuspfadt** [comment]
> * [ ]  * cor_test() also has an argument 'nugget.scale'. I think it would be good to add it to the module as well (maybe set the default to .999 or something). In case of very small samples and extreme observations, e.g., when the cor estimate is very close to 1, the MCMC sometimes gets stuck close to 1, and this nugget.scale would fix that by setting it to a slightly smaller value if needed. I can add info in the help file on this of course.
okay

> * [ ]  * For the independent samples t-test, include an option var.equal=TRUE/FALSE (default TRUE). In case var.equal=FALSE, the iter argument (default 1e6) is used, and thus, would be needed as an additional option in that case.
Okay, what would you call that option? Just Iterations? 

> * [ ]  * In the independent samples t-test, I see infinity in the second last 'BF' column in the specification table. I do not see this in the 'BFtable_confirmatory' element of the BF object in R. Do you compute it manually in the module? Maybe better to extract it from the 'BFtable_confirmatory' element of the BF object?
We have the table in this line https://github.com/juliuspfadt/jaspBfpack/blob/c608c796d01c9d9706534969b7e7b0fc34e3eada/R/bfpackcommon.R#L812. Maybe it is a super large number? I dont know what example you are referring to.

> * [ ]  * For the linear regression model and (M)AN(C)OVA, it would be nice to include a checkbox of whether the scale variables need to be standardized. In bain, this is more complex because standardization can be done in different ways in a SEM (I think). But here it is just very straightforward by standardizing the dependent/predictor variables with scale measurement level. The reason that this is particularly useful is because when testing coefficients in a regression model, say, beta1>beta2, this only makes sense if the scale of the predictors is the same.
Okay. I had already inquired about this in a previous email but you didn't respond anymore so I thought that was not necessary. Anyways, you would want a button for which all variables that have continuous level are standardised before the analysis, with `scale()` for example?

> * [x]  * For the logistic regression model, it would be nice if it can handle a nominal DV having two levels (via a glm() base analysis), as well as an ordinal DV (via a MASS::polr() analysis). I think you already implemented though...
> * [ ]  * Multivariate t test. JASP does not do anything when only one variable is included. Maybe we want to keep it this way but in R, a simple t test would be executed then (without needing to change the syntax for the multivariate t test using the mvt_test() function).
Should be possible.
> * [ ]  * Multivariate t test. Test values cannot be aligned? Sorry for this question if you already told me...
That is next to impossible because we dont know how much space the variable names would take.

**Comment by jomulder** [comment]
> > * [ ]   * cor_test() also has an argument 'nugget.scale'. I think it would be good to add it to the module as well (maybe set the default to .999 or something). In case of very small samples and extreme observations, e.g., when the cor estimate is very close to 1, the MCMC sometimes gets stuck close to 1, and this nugget.scale would fix that by setting it to a slightly smaller value if needed. I can add info in the help file on this of course.
> 
> okay
> 
> > * [ ]   * For the independent samples t-test, include an option var.equal=TRUE/FALSE (default TRUE). In case var.equal=FALSE, the iter argument (default 1e6) is used, and thus, would be needed as an additional option in that case.
> 
> Okay, what would you call that option? Just Iterations?

Yes, for instance. Btw I just realize that for multivariate regression and MANCOVA, an iteration option is also present, again via the 'iter' argument in BF(). In R the default is 10000, which we could also use here. This 'iter' argument is only used for certain types of constrained hypothese for which no exact expression is available. I will add it in the above list.

> 
> > * [ ]   * In the independent samples t-test, I see infinity in the second last 'BF' column in the specification table. I do not see this in the 'BFtable_confirmatory' element of the BF object in R. Do you compute it manually in the module? Maybe better to extract it from the 'BFtable_confirmatory' element of the BF object?
> 
> We use the table, see in this line https://github.com/juliuspfadt/jaspBfpack/blob/c608c796d01c9d9706534969b7e7b0fc34e3eada/R/bfpackcommon.R#L812. Maybe it is a super large number? I dont know what example you are referring to.
> 

Ok, looks fine. Maybe I can retrieve an example.

> > * [ ]   * For the linear regression model and (M)AN(C)OVA, it would be nice to include a checkbox of whether the scale variables need to be standardized. In bain, this is more complex because standardization can be done in different ways in a SEM (I think). But here it is just very straightforward by standardizing the dependent/predictor variables with scale measurement level. The reason that this is particularly useful is because when testing coefficients in a regression model, say, beta1>beta2, this only makes sense if the scale of the predictors is the same.
> 
> Okay. I had already inquired about this in a previous email but you didn't respond anymore so I thought that was not necessary. Anyways, you would want a button for which all variables that have continuous level are standardised before the analysis, with `scale()` for example?
> 

Yes indeed. And sorry about that. Apparently I forgot to reply to that email.

> > * [ ]   * Multivariate t test. JASP does not do anything when only one variable is included. Maybe we want to keep it this way but in R, a simple t test would be executed then (without needing to change the syntax for the multivariate t test using the mvt_test() function).
> 
> Should be possible.
> 
> > * [ ]   * Multivariate t test. Test values cannot be aligned? Sorry for this question if you already told me...
> 
> That is next to impossible because we dont know how much space the variable names would take.

Ok sorry, forget about this.

**Comment by jomulder** [comment]
Hi Julius, thanks for informing me. I (think) am done with the help files.
You received/saw the push/pulls, or how do I call those?

About the error, are you saying that you get an error when running
get_estimates on the output object of a mvt_test object? In R I do not get
any errors...

Best,
Joris

**Comment by jomulder** [comment]
Btw I would then update the help files a bit here and there for the extra
options you added. Will do that next week.
Best,
Joris

**Comment by juliuspfadt** [comment]
about the mvt so this does not work
```
library(BFpack)
dt <- read.csv("https://raw.githubusercontent.com/jasp-stats/jasp-desktop/development/Resources/Data%20Sets/debug.csv")
test <- mvt_test(dt$contNormal)
BFpack:::get_estimates.mvt_test(test)
```
 but this works
```
library(BFpack)
dt <- read.csv("https://raw.githubusercontent.com/jasp-stats/jasp-desktop/development/Resources/Data%20Sets/debug.csv")
test <- mvt_test(dt$contNormal)
get_estimates(test)
```
The reason (I think) is that this defaults back to the one.sample t-test call. 
But in the module I always explicitly call these functions like in the first example. I can't exactly remember the reason why, but there was one... I suppose I could just implement an exception for one variable.

**Comment by juliuspfadt** [comment]
Regarding your GitHub workflow... I think you should not do what you are doing, because it looks like you are creating new branches for each new help file. So eventually, we will have to just collect all help files from all these branches and copy paste them into the actual module. In that case it is equally sensible to just change the .md files locally and send them to me. I am sorry I made you do this :(

**Comment by jomulder** [comment]
Hi Julius, hmmm ok. I never tried the first option to be honest because the
function is not hidden. But admittedly, I also don’t see why the option
would not work while the second would work (because they should be the same
right?).
Best,
Joris

**Comment by juliuspfadt** [comment]
in the second case you call `bain` under the hood. but can you maybe send me the R code for the mvt_test for which you say it works? seems like I am also getting an error for the second example because of the way I specify the priors

**Comment by juliuspfadt** [comment]
Ah I see, when I have more than one variable we are testing mu1 = mu2 and the test only allows two prior weights, for equality and inequality. But when there is only one variable, the test defaults back to the one sample t-test and for that one Bfpack actually expected three prior weights, equality, smaller and larger.

**Comment by juliuspfadt** [comment]
tbh, it would be much simpler to just only allow >= 2

**Comment by jomulder** [comment]
I just read you comment on the .md files. So then I will download those
files and send you complete updated versions? Just checking to be sure.

About the mvt_test for a univariate dv, ah yes, that’s indeed confusing. I
could change this in R, but I also think it fine like that (although I
understand the frustration/unclarity…).

About allowing “>=2”, do you mean to allow hypotheses that state that, say,
mu is larger than or equal to 2, as an alternative to stating that mu is
(only) larger than 2? Not sure why this would be beneficial (probably I am
missing your point…). The reason for not allowing this choice though is
that the marginal likelihood for “mu>2” and “mu>=2” given a (standard)
continuous (so not spike-slab) prior is identical because mu=2 has zero
probability. But I am not sure if this addresses your point..?

Best,
Joris

**Comment by juliuspfadt** [comment]
I meant at least two variables :)

**Comment by jomulder** [comment]
Ah yes, of course we could have that restriction in jasp :)

**Comment by jomulder** [comment]
But in that case, the multivariate t test works fine as it does not do
anything in case only one variable is included as DV. So we can mention
this in the help.
Best,
Joris

**Comment by juliuspfadt** [comment]
and yes send the help files just as an mail or something.

**Comment by jomulder** [comment]
Will do...
